#!/bin/bash
colmap=/home/mifs/fx221/Research/Software/bin/colmap

dataset=/scratches/flyer_2/fx221/localization/aachen_v1_1
outputs=/scratches/flyer_2/fx221/localization/outputs/aachen_v1_1

#feat=superpoint-n2000-r1024-mask
#feat=superpoint-n4096-r1024
#feat=superpoint-n4096-r1024-mask
#feat=r2d2-n4096-r1024-mask
#feat=spd2l2net-ms-n4096-r1024-0001-mask
#feat=r2d2-rmax1600-10k-mask
#feat=resnete2-n4096-r1600-0005-mask
#feat=resnete2-ms-n4096-r1600-001-mask
#feat=resnete2-ms-n10000-r1600-0005-mask
#feat=resnete2-ap-ms-n4096-r1600-001
#feat=resnete2-ap-ms-n4096-r1600-001-mask
#feat=resnete2-ap-n4096-r1600-0005-mask

#feat=resnete2-ap-n10000-r1600-0005-mask
#feat=resnete2-ap-n4096-r1600-001-mask
#feat=resnete2-ap-n10000-r1600-001-mask
#feat=resnete2-ap-n3000-r1600-001-mask

#feat=resnete2-tr-n3000-r1600-001-mask
#feat=resnete2-tr-n4096-r1600-001-mask
#feat=resnete2-tr-n3000-r1600-0005-mask
feat=resnete2-tr-n4096-r1600-0005-mask
#feat=resnete2-tr-n2000-r1600-0005-mask
#feat=resnete2-tr-n1000-r1600-0005-mask

#feat=resnete2-tr-n3000-r1600-0005
#feat=resnete2-tr-n4096-r1600-0005


image_dir=$dataset/images/images_upright
mask_dir=scratches/flyer_2/fx221/localization/aachen_v1_1/global_seg_instance

matcher=NNML
#matcher=NNM

extract_feat=1
match_db=1

if [ "$extract_feat" -gt "0" ]; then
  python3 -m localization.fine.extractor --image_dir $image_dir --export_dir $outputs/ --conf $feat --mask_dir $mask_dir
fi

if [ "$match_db" -gt "0" ]; then
  python3 -m localization.fine.matcher --pairs datasets/aachen/pairs-db-covis20.txt --export_dir $outputs/ --conf $matcher --features feats-$feat
fi