#!/bin/bash
colmap=/home/mifs/fx221/Research/Software/bin/colmap

#root_dir=/scratches/flyer_2
root_dir=/scratch2

dataset=$root_dir/fx221/localization/RobotCar-Seasons
outputs=$root_dir/fx221/localization/outputs/robotcar
db_pair=$root_dir/fx221/localization/outputs/robotcar/pairs-db-covis20.txt

#feat=superpoint-n2000-r1024-mask
#feat=superpoint-n4096-r1024
#feat=superpoint-n4096-r1024-mask
#feat=r2d2-n4096-r1024-mask
#feat=spd2l2net-ms-n4096-r1024-0001-mask
#feat=r2d2-rmax1600-10k-mask
#feat=resnete2-n4096-r1600-0005-mask
#feat=resnete2-ms-n4096-r1600-001-mask
#feat=resnete2-ms-n10000-r1600-0005-mask
#feat=resnete2-ap-ms-n4096-r1600-001
#feat=resnete2-ap-ms-n4096-r1600-001-mask

#feat=resnete2-ap-n10000-r1600-001-mask
#feat=resnete2-ap-n10000-r1600-0005-mask
#feat=resnete2-ap-n4096-r1600-001-mask
#feat=resnete2-ap-n4096-r1024-0005-mask
#feat=resnete2-ap-n3000-r1600-001-mask


#feat=resnete2-tr-n4096-r1024-0015-mask
#feat=resnete2-tr-n3000-r1024-001-mask
#feat=resnete2-tr-n4096-r1024-001-mask
#feat=resnete2-tr-n3000-r1024-0005-mask
feat=resnete2-tr-n4096-r1024-0005-mask
#feat=resnete2-ms-tr-n4096-r1024-0005-mask
#feat=resnete2-ms-tr-n3000-r1024-0005-mask


#feat=resnete2-msu-tr-n4096-r1024-0005-mask

mask_dir=$root_dir/fx221/exp/shloc/robotcar/2021_10_17_00_21_32_robotcar_pspf_resnext101_32x4d_d4_u8_b16_R256_E500_ceohem_adam_poly_mlr_seg_cls_aug_stylized/masks

matcher=NNML
#matcher=NNM

extract_feat_db=1
match_db=1

if [ "$extract_feat" -gt "0" ]; then
  python3 -m localization.fine.extractor --image_list datasets/robotcar/robotcar_db_query_imglist.txt --image_dir $dataset/images --export_dir $outputs/ --conf $feat --mask_dir $mask_dir
fi

if [ "$match_db" -gt "0" ]; then
  python3 -m localization.fine.matcher --pairs $db_pair --export_dir $outputs/ --conf $matcher --features feats-$feat
fi