#!/bin/bash
colmap=/home/mifs/fx221/Research/Software/bin/colmap

root_dir=/scratch2

dataset=$root_dir/fx221/localization/RobotCar-Seasons
outputs=$root_dir/fx221/localization/outputs/robotcar
db_pair=$root_dir/fx221/localization/outputs/robotcar/pairs-db-covis20.txt

feat=resnetxn-triv2-ms-0001-n4096-r1024-mask

mask_dir=$root_dir/fx221/exp/shloc/robotcar/2021_10_17_00_21_32_robotcar_pspf_resnext101_32x4d_d4_u8_b16_R256_E500_ceohem_adam_poly_mlr_seg_cls_aug_stylized/masks

matcher=NNML
#matcher=NNM

extract_feat_db=1
match_db=1
triangulate=1

if [ "$extract_feat" -gt "0" ]; then
  python3 -m localization.fine.extractor --image_list datasets/robotcar/robotcar_db_query_imglist.txt --image_dir $dataset/images --export_dir $outputs/ --conf $feat --mask_dir $mask_dir
fi

if [ "$match_db" -gt "0" ]; then
  python3 -m localization.fine.matcher --pairs $db_pair --export_dir $outputs/ --conf $matcher --features feats-$feat
fi

if [ "$triangulate" -gt "0" ]; then
  python3 -m localization.fine.triangulate \
    --sfm_dir $outputs/sfm_$feat-$matcher \
    --reference_sfm_model $ROBOTCAR/3D-models/sfm-sift \
    --image_dir $ROBOTCAR/images \
    --pairs $outputs/pairs-db-covis20.txt \
    --features $outputs/feats-$feat.h5 \
    --matches $outputs/feats-$feat-$matcher-pairs-db-covis20.h5 \
    --colmap_path $colmap
fi