#!/bin/bash
#root=/scratch2
root=/scratches/flyer_2

outputs=$root/fx221/localization/outputs/robotcar
dataset=$root/fx221/localization/RobotCar-Seasons
save_root=$root/fx221/exp/shloc/robotcar

image_dir=$root/fx221/localization/RobotCar-Seasons/images
weight_name=2021_10_17_00_21_32_robotcar_pspf_resnext101_32x4d_d4_u8_b16_R256_E500_ceohem_adam_poly_mlr_seg_cls_aug_stylized
seg_dir=$root/fx221/exp/shloc/robotcar/$weight_name/masks


query_fn=$dataset/queries_with_intrinsics_rear.txt
query_pair=datasets/robotcar/pairs-query-netvlad20-percam-perloc-rear.txt
gt_pose_fn=/data/cornucopia/fx221/localization/RobotCar-Seasons/3D-models/query_poses_v2.txt


#feat=resnete2-ms-n10000-r1600-0005-mask
#feat=resnete2-n4096-r1600-0005-mask

#feat=resnete2-ap-n3000-r1600-001-mask
#feat=resnete2-ap-n4096-r1600-001-mask
#feat=resnete2-ap-n10000-r1600-001-mask
#feat=resnete2-ap-n4096-r1024-0005-mask



#feat=resnete2-tr-n3000-r1024-001-mask
#feat=resnete2-tr-n4096-r1024-001-mask
#feat=resnete2-tr-n3000-r1024-0005-mask
#feat=resnete2-ms-tr-n3000-r1024-0005-mask

#feat=resnete2-tr-n4096-r1024-0005-mask
#feat=resnete2-ms-tr-n4096-r1024-0005-mask

#feat=resnetxn-ori-0005-n4096-r1024-mask
#feat=resnetxn-triv2-0001-n4096-r1024-mask
feat=resnetxn-triv2-ms-0001-n4096-r1024-mask

#matcher=NNM
matcher=NNML

only_gt=0
feature_type="feat_max"
global_score_th=0.95

rec_th=200
nv_th=50
ransac_thresh=12
opt_thresh=8
covisibility_frame=20
init_type="clu"
retrieval_type="lrnv"
opt_type="clurefpos"
k_seg=10
k_can=1
k_rec=20
iters=5
radius=20
obs_thresh=3

# with opt
python3 -m localization.localizer \
    --only_gt $only_gt \
    --retrieval_type $retrieval_type \
    --gt_pose_fn $gt_pose_fn \
    --image_dir $image_dir \
    --seg_dir $seg_dir \
    --dataset robotcar \
    --map_gid_rgb_fn datasets/robotcar/robotcar_grgb_gid.txt \
    --db_imglist_fn  datasets/robotcar/robotcar_rear_db_imglist.txt \
    --db_instance_fn robotcar \
    --save_root $save_root \
    --k_seg $k_seg \
    --k_can $k_can \
    --k_rec $k_rec \
    --feature_type $feature_type \
    --init_type $init_type \
    --global_score_th $global_score_th \
    --weight_name $weight_name \
    --show_seg \
    --reference_sfm $outputs/sfm_$feat-$matcher/model \
    --queries $query_fn \
    --retrieval $query_pair \
    --features $outputs/feats-$feat.h5 \
    --matcher_method $matcher \
    --ransac_thresh $ransac_thresh \
    --with_label \
    --with_match \
    --rec_th $rec_th \
    --nv_th $nv_th \
    --covisibility_frame $covisibility_frame \
    --iters $iters \
    --radius $radius \
    --obs_thresh $obs_thresh \
    --opt_thresh $opt_thresh \
    --opt_type $opt_type \
    --do_covisible_opt